### ISSUE TITLE
Bintray repository no longer available

### ISSUE THREAD

**Issue by Enet4** [andriimartynov/sbt-terser#3]
The Bintray public package repository had been slowly phasing out since March 2021, and now it is completely shut down, making this plugin unreachable.

Could you please consider deploying the artifact somewhere else?

**Comment by andriimartynov** [comment]
Hello @Enet4. What version of sbt do you have?


> There’s now a cloud-hosted Artifactory instance licensed to Scala Center, and fully sponsored by JFrog. Let’s call this “Artsy” in this post instead of the Artifactory instance. With the release of sbt 1.5.1, I think we can say that the migration is done.
read side
As of April 18th, I have migrated all sbt plugins and sbt 0.13 artifacts to Artsy, and Lightbend IT team has redirected https://repo.scala-sbt.org/scalasbt/ to point to Artsy as well, so existing builds should continue to work without making any changes today and after May 1st. Please check for [an issue](https://github.com/sbt/sbt/issues), and report it if this is not the case.


https://eed3si9n.com/bintray-to-jfrog-artifactory-migration-status-and-sbt-1.5.1


https://scala.jfrog.io/ui/repos/tree/General/sbt-plugin-releases/com.github.andriimartynov/sbt-terser/scala_2.12/sbt_1.0/0.0.1

**Comment by Enet4** [comment]
Ah, it is great to know that this migration took place! The readme still points to bintray, which led to the confusion.

I am currently not using this plugin, but I might in the future.
